server:
  port: 8080

spring:
  config:
    import: application-config.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/keygo;NON_KEYWORDS=USER;DATABASE_TO_UPPER=false;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true